server:
  port: 8001

spring:
  mongodb:
    uri: mongodb://${MONGO_DB_USERNAME:singularity}:${MONGO_DB_PASSWORD:singularity}@${MONGO_DB_HOST:localhost}:${MONGO_DB_PORT:27017}/${MONGO_DB_DATABASE_NAME:test-application}?authSource=admin&tls=false
    representation:
      uuid: standard

  data:
    redis:
      host: localhost
      port: 6379
      password: singularity
      database: 0
      timeout: 5000ms
      ssl:
        enabled: false
  devtools:
    restart:
      enabled: false
      additional-paths: src/main
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: client-id
            client-secret: client-secret
            scope:
              - user:email
              - read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code


logging:
  level:
    io.stereov: DEBUG

singularity:
  app:
    name: TestApplication
    base-url: http://localhost:8000
    support-mail: support@example.com
    secure: false
    create-root-user: false
    root-email: ${ROOT_EMAIL}
    root-password: ${ROOT_PASSWORD}
  email:
    enable: false
  auth:
    two-factor:
      totp:
        recovery-code:
          length: 10
          count: 6
      email:
        enable-by-default: false
    oauth2:
      enable: true

  file:
    storage:
      type: local
      local:
        file-directory: .data/test/files
  secrets:
    store: local
    local:
      secret-directory: ./.data/test/secrets
    key-rotation-cron: 0 0 4 1 1,4,7,10 *
    cache-expiration: 900000
  security:
    jwt:
      expires-in: 900
    rate-limit:
      ip-limit: 10000
      ip-time-window: 1
      user-limit: 10000
      user-time-window: 1
    login-attempt-limit:
      ip-limit: 10000
      ip-time-window: 1
  ui:
    base-url: http://localhost:4200
