name: Build and Test

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'libs/**'
      - '.github/workflows/build-and-test.yml'
      - '**/*gradle*'
      - '**/gradle/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'libs/**'
      - '.github/workflows/build-and-test.yml'
      - '**/*gradle*'
      - '**/gradle/**'

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      MAXMIND_ACCOUNT_ID: ${{ secrets.MAXMIND_ACCOUNT_ID }}
      MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          ./gradlew assemble

      - name: Run Tests
        run: |
          ./gradlew test

      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          require_tests: true
          include_passed: false

  demo_image:
    name: Build and Push Demo Image
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: harbor.stereov.io
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/demo/Dockerfile
          platforms: linux/amd64
          push: false
          tags: harbor.stereov.io/singularity/demo:${{ github.sha }}

      - name: Build and push image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/demo/Dockerfile
          platforms: linux/amd64
          push: true
          tags: harbor.stereov.io/singularity/demo:${{ github.sha }}

  stereov-io:
    name: Build stereov-io
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: harbor.stereov.io
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/stereov-io/Dockerfile
          platforms: linux/amd64
          push: false
          tags: harbor.stereov.io/stereov-io/singularity:${{ github.sha }}

      - name: Build and push image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/stereov-io/Dockerfile
          platforms: linux/amd64
          push: true
          tags: harbor.stereov.io/stereov-io/singularity:${{ github.sha }}
