name: Deploy Docusaurus and Demo

on:
  push:
    paths:
      - 'libs/core/**'
      - 'apps/demo/**'
      - '.github/workflows/deploy-docs.yml'
      - 'docs/**'
    branches:
      - main

jobs:
  docs:
    name: Build and Deploy Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: 'docs/yarn.lock'
      - name: Install yarn
        working-directory: docs
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: docs
      - name: Create production build
        run: yarn build
        working-directory: docs

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: harbor.stereov.io
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docusaurus Image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: ./docs
          file: ./docs/Dockerfile
          platforms: linux/amd64
          push: false
          tags: harbor.stereov.io/singularity/docs:${{ github.sha }}

      - name: Build and Push Docusaurus Image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: ./docs
          file: ./docs/Dockerfile
          platforms: linux/amd64
          push: true
          tags: harbor.stereov.io/singularity/docs:${{ github.sha }}

      - name: Checkout ArgoCD Repo
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: antistereov/k8s-clusters
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops-config

      - name: Update Manifest
        if: github.event_name == 'push'
        working-directory: ./gitops-config
        run: |
          yq -i 'select(.kind == "Deployment") .spec.template.spec.containers[0].image = "harbor.stereov.io/singularity/docs:${{ github.sha }}"' apps/singularity/docs/deployment.yaml

      - name: Commit and Push
        if: github.event_name == 'push'
        working-directory: ./gitops-config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(singularity): update docs image to ${{ github.sha }}"
          git push
